/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-04-05 13:56:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.function;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import web.util.*;
import java.util.*;
import web.bean.*;

public final class Cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("web.util");
    _jspx_imports_packages.add("web.bean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>购物车</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/header.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("\t.sptp{width:80x;\r\n");
      out.write("\theight:80px;}\r\n");
      out.write("\t.total{\r\n");
      out.write("\tmargin-left:35%;\r\n");
      out.write("\theight:20px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../template/_header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"oitemlist\" style=\"min-height:300px;margin:0 auto;position:relative;left:160px;\">\r\n");
      out.write("\t\t<div style=\"margin:0 auto;width:90%;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><b></b></th>\r\n");
      out.write("\t\t\t\t\t<th><b>商品</b></th>\r\n");
      out.write("\t\t\t\t\t<th><b>单价</b></th>\r\n");
      out.write("\t\t\t\t\t<th><b>数量</b></th>\r\n");
      out.write("\t\t\t\t\t<th><b>价格</b></th>\r\n");
      out.write("\t\t\t\t\t<th><b>删除</b></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
Cart cart = web.util.RequestAttrHelper.getCartObject(request);
      out.write("\r\n");
      out.write("\t\t\t\t");
List<OrderItem> buylist = cart.getItems();
      out.write("\r\n");
      out.write("\t\t\t\t");
 double total =0;
      out.write("\r\n");
      out.write("\t\t\t\t");

					for(int idx = 0 ; idx < buylist.size(); idx++){
							OrderItem anOrder = buylist.get(idx);
							Commodity cd = anOrder.getCommodity();
							if(cd!=null){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><b><img class=\"sptp\" src=\"");
      out.print(cd.getImage());
      out.write("\"/></b></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><b>");
      out.print(cd.getName());
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><b>");
      out.print(Numeric.toFixedDecimalString(cd.getPrice(), 2));
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><b>");
      out.print(anOrder.getQuantity());
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><b>");
      out.print(Numeric.toFixedDecimalString(cd.getPrice()*anOrder.getQuantity(),2) );
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><form name=\"deleteForm\" action=\"CartServlet\" method=\"POST\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Delete\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"delindex\" value='");
      out.print(idx);
      out.write("'> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"Delete\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
 total=total+cd.getPrice()*anOrder.getQuantity();
      out.write("\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div class=\"total\">合计￥");
      out.print(total );
      out.write("</div>\r\n");
      out.write("\t\t\t<form name=\"checkoutForm\" action=\"CartServlet\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"Checkout\"> \r\n");
      out.write("\t\t\t\t<div class=\"form-item\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-ctrl\" >\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" name=\"Checkout\" value=\"去结算\" class=\"btn-green center-block\" style=\"width:240px;background-color:orange;color:black;margin:5px auto;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../template/_bottom.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
