/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-03-30 09:42:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import web.bean.*;
import web.util.*;
import web.service.*;
import web.dao.impl.*;
import web.dao.*;
import web.controller.*;
import web.controller.helper.*;

public final class _005fheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("web.dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("web.controller");
    _jspx_imports_packages.add("web.controller.helper");
    _jspx_imports_packages.add("web.util");
    _jspx_imports_packages.add("web.bean");
    _jspx_imports_packages.add("web.dao.impl");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("web.service");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<base href=\"");
      out.print(web.util.BasePath.get(request));
      out.write("\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/header.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("#plus{\r\n");
      out.write("width:190px;\r\n");
      out.write("border: 1px solid #00a4ff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>       \r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("            <div class=\"logo\"><img src=\"images/logo.jpg\" /></div>\r\n");
      out.write("            <div class=\"nav\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"home\">首页</a></li>\r\n");
      out.write("                    <li><a href=\"jsp/demo/schoolmarket.jsp\">校园超市</a></li>\r\n");
      out.write("                    <li><a href=\"jsp/demo/nearbyshops.jsp\">附近商家</a></li>\r\n");
      out.write("                    <li><a href=\"jsp/demo/shopview.jsp\">商品速览</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"search\">\r\n");
      out.write("            \t\t<form name=\"search\" action=\"SearchServlet\" method=\"post\">\r\n");
      out.write("                   \t<input  type=\"text\" class=\"text1\" name=\"search\" id=\"search_01\" placeholder=\"请输入关键字\" >\r\n");
      out.write("                   \t<input id=\"button\" type=\"submit\" value=\"\"/>\r\n");
      out.write("                   \t<input  type=\"hidden\" name=\"action\" value=\"search\"/>\r\n");
      out.write("                   \t\r\n");
      out.write("                    <div id=\"plus\"></div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   ");
String cn =null; 
      out.write("\r\n");
      out.write("                    <script>\r\n");
      out.write("                    var input = document.getElementById(\"search_01\");\r\n");
      out.write("                \tinput.addEventListener(\"input\",inputLoad,false);\r\n");
      out.write("                \tfunction inputLoad(e){\r\n");
      out.write("                \t\tvar con = e.data;\t\r\n");
      out.write("                \t\tcn = con;\r\n");
      out.write("                \t\tif(cn!=null){\r\n");
      out.write("                \t\tvar tem = document.getElementById(\"plus\");\r\n");
      out.write("                \t\ttem.innerHTML = cn;\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t}\r\n");
      out.write("                    </script>\r\n");
      out.write("                   \r\n");
      out.write("                    <script>\r\n");
      out.write("                    \tinputLoad(input);\r\n");
      out.write("                    </script>\r\n");
      out.write("          \r\n");
      out.write("            <div class=\"personal\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                \t<li><a id=\"toOrder\" href=\"admin/login.jsp\">卖家服务</a></li>\r\n");
      out.write("                \t<li><a id=\"toOrder\" href=\"CartServlet?action=ShowOrder\">订单</a></li>\r\n");
      out.write("                    <li><a id=\"toCart\" href=\"CartServlet?action=ShowCart\">购物车</a></li>\r\n");
      out.write("                    <li><img src=\"images/gwc.jpg\" alt=\"购物车\"></li>\r\n");
      out.write("                    <li><img src=\"images/id.jpeg\" alt=\"帅照\"></li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                     <form name=\"logout\" action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t ");
 boolean islogin = web.service.AuthHelper.isLogin(request.getSession());
      out.write("\r\n");
      out.write("\t\t\t\t\t <input type=\"hidden\" name=\"action\" value=\"");
      out.print( (islogin?"logout":"login"));
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t <input type=\"submit\" name=\"Submit\" value=\"");
      out.print( (islogin?"注销":"登录"));
      out.write("\" class=\"btn-green ctrl-button\">\t\r\n");
      out.write("\t\t\t     \t</form>\r\n");
      out.write("\t\t\t     \t</li>\r\n");
      out.write("                 \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
