/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2021-04-14 11:53:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.demo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;
import web.bean.*;
import web.util.*;
import web.service.*;
import web.dao.impl.*;
import web.dao.*;
import web.controller.*;
import web.controller.helper.*;

public final class smilk_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("web.dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("web.controller");
    _jspx_imports_packages.add("web.controller.helper");
    _jspx_imports_packages.add("web.util");
    _jspx_imports_packages.add("web.bean");
    _jspx_imports_packages.add("web.dao.impl");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("web.service");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>酸奶</title>\r\n");
      out.write("<base href=\"");
      out.print(web.util.BasePath.get(request));
      out.write("\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/header.css\" />\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"css/shopclass.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../template/_header.jsp", out, false);
      out.write("\r\n");
      out.write("\t  <!-- 商品分类页开始 -->\r\n");
      out.write("        <div class=\"spfl\">\r\n");
      out.write("            <div class=\"spfl-left\">\r\n");
      out.write("                <div class=\"subnav\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li style=\"color:#fff;\">商品分类</li>\r\n");
      out.write("                        <li><a href=\"#\">君乐宝开啡尔<span> > </span></a>\r\n");
      out.write("                            <div class=\"subnav-fl\">\r\n");
      out.write("                                <div class=\"boder\">\r\n");
      out.write("                                    <div><p>&emsp;&nbsp;酸奶</p> </div>\r\n");
      out.write("                                    <div class=\"sg\">\r\n");
      out.write("\r\n");
      out.write("                                        <ul>                               \r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <div>\r\n");
      out.write("                                                    <div class=\"p-image\"><img src=\"images/sn_kfe.jpg\" /></div>                                            \r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>                                        \r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>    \r\n");
      out.write("                                                        \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\">新希望若雪<span> > </span></a>\r\n");
      out.write("                            <div class=\"subnav-fl\">\r\n");
      out.write("                                <div class=\"boder\">\r\n");
      out.write("                                    <div><p>&emsp;&nbsp;酸奶</p> </div>\r\n");
      out.write("                                    <div class=\"sg\">\r\n");
      out.write("\r\n");
      out.write("                                        <ul>                               \r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <div>\r\n");
      out.write("                                                    <div class=\"p-image\"><img src=\"images/sn_rx.jpg\" /></div>                                            \r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>    \r\n");
      out.write("                                                       \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\">蒙牛纯甄<span> > </span></a>\r\n");
      out.write("                            <div class=\"subnav-fl\">\r\n");
      out.write("                                <div class=\"boder\">\r\n");
      out.write("                                    <div><p>&emsp;&nbsp;酸奶</p> </div>\r\n");
      out.write("                                    <div class=\"sg\">\r\n");
      out.write("\r\n");
      out.write("                                        <ul>                               \r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <div>\r\n");
      out.write("                                                    <div class=\"p-image\"><img src=\"images/sn_cz.jpg\" /></div>                                            \r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>    \r\n");
      out.write("                                                    \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>                     \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"spfl-right\">\r\n");
      out.write("                <div class=\"product-max\">\r\n");
      out.write("\t \t\t\t");

	 				ICommodityDao dao = new CommodityDaoImpl(); List<Commodity> cf =dao.queryType("酸奶");
	 			
      out.write(" \r\n");
      out.write("\t \t\t\t");
for( int i=0;i<cf.size();i++){
      out.write("\t\t\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li>\r\n");
      out.write("                           <div>\r\n");
      out.write("                              <div class=\"p-image\"><a href=\"CommodityServlet?action=show&id=");
      out.print(cf.get(i).getId());
      out.write("\"><img src=\"");
      out.print(cf.get(i).getImage());
      out.write("\" /></a></div>      \r\n");
      out.write("                                  \t <div class=\"head\">");
      out.print(cf.get(i).getName() );
      out.write(' ');
      out.print(Numeric.toFixedDecimalString(cf.get(i).getPrice(), 2) );
      out.write("元\r\n");
      out.write("                                  \t \t<a class=\"person\" id=\"toCart\" href=\"CartServlet?action=add&id=");
      out.print(cf.get(i).getId());
      out.write("\"><img src=\"images/gwc.jpg\" alt=\"购物车\"></a>\r\n");
      out.write("                                  \t\t\r\n");
      out.write("                                  \t </div>\r\n");
      out.write("                                 \t\t<p>\r\n");
      out.write("                                \t\t\t  总销量<span>");
      out.print(cf.get(i).getTotalamount() );
      out.write("</span>\r\n");
      out.write("                              \t\t\t</p>\t \r\n");
      out.write("                          </div>\r\n");
      out.write("                           </li>\r\n");
      out.write("                       ");
 };
      out.write("\r\n");
      out.write("                     </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 商品分类页结束 -->\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
