/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2021-04-14 11:09:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import web.bean.*;
import web.util.*;
import web.service.*;
import web.dao.impl.*;
import web.dao.*;
import web.controller.*;
import web.controller.helper.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("web.dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("web.controller");
    _jspx_imports_packages.add("web.controller.helper");
    _jspx_imports_packages.add("web.util");
    _jspx_imports_packages.add("web.bean");
    _jspx_imports_packages.add("web.dao.impl");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("web.service");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>天猫超市乳饮品</title>\r\n");
      out.write("\t<base href=\"");
      out.print(web.util.BasePath.get(request));
      out.write("\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\" />\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#progress{\r\n");
      out.write("\t\t\t\tposition:fixed;\r\n");
      out.write("\t\t\t\tbackground:#000;\r\n");
      out.write("\t\t\t\ttop:0;\r\n");
      out.write("\t\t\t\tleft:0;\r\n");
      out.write("\t\t\t\twidth:100%;\r\n");
      out.write("\t\t\t\theight:100%;\r\n");
      out.write("\t\t\t\tz-index:9999;\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t#progress p{\r\n");
      out.write("\t\t\t\twidth:500px;\r\n");
      out.write("\t\t\t\theight:30px;\r\n");
      out.write("\t\t\t\tborder-radius:3px;\r\n");
      out.write("\t\t\t\tbackground:#ffffcc;\r\n");
      out.write("\t\t\t\tcolor:#330000;\r\n");
      out.write("\t\t\t\tfont-size:14px;\r\n");
      out.write("\t\t\t\tline-height:30px;\r\n");
      out.write("\t\t\t\ttext-align:center;\r\n");
      out.write("\t\t\t\toverflow:hidden;\r\n");
      out.write("\t\t\t\tfont-family:'宋体';\r\n");
      out.write("\t\t\t\tposition:absolute;\r\n");
      out.write("\t\t\t\ttop:50%;\r\n");
      out.write("\t\t\t\tleft:50%;\r\n");
      out.write("\t\t\t\tmargin-top:-15px;\r\n");
      out.write("\t\t\t\tmargin-left:-250px;\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t.person{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.person img{width:40px;\r\n");
      out.write("\theight:40px;}\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id='progress'>\r\n");
      out.write("\t\t<p>0%</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar oP=document.getElementById('progress').getElementsByTagName('p')[0];\r\n");
      out.write("\t\tfunction move(num){clearInterval(oP.timer);\r\n");
      out.write("\t\toP.timer = setInterval(function(){\r\n");
      out.write("\t\t\tif (parseInt(oP.innerHTML)<num){\r\n");
      out.write("\t\t\t\tvar s = parseInt(oP.innerHTML)+1;\r\n");
      out.write("\t\t\t\tvar w = 500*s/100;\r\n");
      out.write("\t\t\t\toP.innerHTML = s+'%';\r\n");
      out.write("\t\t\t\toP.style.width = w+'px';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tclearInterval(oP.timer);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},60);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t</script>\r\n");
      out.write("\t ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "jsp/template/_header.jsp", out, false);
      out.write("\r\n");
      out.write("  <!-- banner star -->\r\n");
      out.write("    <div class=\"banner\">\r\n");
      out.write("        <div class=\"in\">\r\n");
      out.write("            <ul class=\"in-ul\">\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/nn_tls.jpg\" alt=\"牛奶\"/></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/nn_jd.jpg\" alt=\"牛奶\"/></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/nn_zgl.jpg\" alt=\"牛奶\"/></a></li>\r\n");
      out.write("                <!-- again! -->\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/yl_kl.jpg\" alt=\"饮料\"/></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/yl_jdb.jpg\" alt=\"饮料\"/></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/yl_ht.jpg\" alt=\"饮料\"/></a></li>\r\n");
      out.write("                <!-- again! -->\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/sn_cz.jpg\" alt=\"酸奶\"/></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/sn_rx.jpg\" alt=\"酸奶\"/></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/sn_kfe.jpg\" alt=\"酸奶\"/></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"in-left\">\r\n");
      out.write("                    <div class=\"subnav\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li style=\"color:#fff;\">商品分类</li>\r\n");
      out.write("                                <li><a href=\"#\">可口可乐<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">营养早餐<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">进口乳饮<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"jsp/demo/drink.jsp\">饮料<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"jsp/demo/milk.jsp\">牛奶<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"jsp/demo/smilk.jsp\">酸奶<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">饮用水<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">啤酒<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">葡萄酒<span> > </span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"in-right\">\r\n");
      out.write("                    <div class=\"subnav\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li style=\"color:#fff;\">爆款好货</li>\r\n");
      out.write("                                <li><a href=\"#\">真果粒四种口味<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">可口可乐迷你装<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">53度飞天茅台<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">国潮AD钙奶<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">伊利金典纯牛奶<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">红牛功能饮料<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">蒙牛纯甄酸奶<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">12瓶装农夫山泉<span> > </span></a></li>\r\n");
      out.write("                                <li><a href=\"#\">康师傅茶饮料<span> > </span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- banner end -->\r\n");
      out.write("    <!-- little banner star -->\r\n");
      out.write("    <div class=\"libanner\">\r\n");
      out.write("        <div class=\"libanner-left\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <div>热门商品</div>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    <!-- libanner end -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"pro\">\r\n");
      out.write("        <div>商品推荐</div>\r\n");
      out.write("        <!-- <a href=\"index.html\">查看全部</a> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- little banner end -->\r\n");
      out.write("    <!-- product begin -->\r\n");
      out.write("    <div class=\"product-max\">\r\n");
      out.write("\t \t\t\t");

	 				ICommodityDao dao = new CommodityDaoImpl(); List<Commodity> cf =dao.query();
	 			
      out.write(" \r\n");
      out.write("\t \t\t\t");
for( int i=0;i<cf.size();i++){
      out.write("\t\t\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li>\r\n");
      out.write("                           <div>\r\n");
      out.write("                              <div class=\"p-image\"><a href=\"CommodityServlet?action=show&id=");
      out.print(cf.get(i).getId());
      out.write("\"><img src=\"");
      out.print(cf.get(i).getImage());
      out.write("\" /></a></div>      \r\n");
      out.write("                                  \t <div class=\"head\">");
      out.print(cf.get(i).getName() );
      out.write(' ');
      out.print(Numeric.toFixedDecimalString(cf.get(i).getPrice(), 2) );
      out.write("元\r\n");
      out.write("                                  \t \t<a class=\"person\" id=\"toCart\" href=\"CartServlet?action=add&id=");
      out.print(cf.get(i).getId());
      out.write("\"><img src=\"images/gwc.jpg\" alt=\"购物车\"></a>\r\n");
      out.write("                                  \t\t\r\n");
      out.write("                                  \t </div>\r\n");
      out.write("                                 \t\t<p>\r\n");
      out.write("                                \t\t\t 总销量<span>");
      out.print(cf.get(i).getTotalamount() );
      out.write("</span>\r\n");
      out.write("                              \t\t\t</p>\t \r\n");
      out.write("                          </div>\r\n");
      out.write("                           </li>\r\n");
      out.write("                       ");
 };
      out.write("\r\n");
      out.write("                     </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("   <!-- product end -->\r\n");
      out.write("    <!-- footer start -->\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("    \t<script>\r\n");
      out.write("    \tmove(100);\r\n");
      out.write("    \tdocument.getElementById(\"progress\").style.display=\"none\";\r\n");
      out.write("    \t</script>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "jsp/template/_bottom.jsp", out, false);
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
